### ISSUE TITLE
Problem with the download button

### ISSUE THREAD

**Issue by kaizenGG** [taxicat1/Plex-downloader#1]
I have tested the script in both Firefox and Chrome, but I have a small problem and that is that the download button "does not work"

![G28ysDi](https://github.com/taxicat1/Plex-downloader/assets/23583436/7c9ceedb-2af9-4c9e-806f-fba00f57b706)

**Comment by taxicat1** [comment]
First, are there any exceptions or error logs printed in the developer console? To view this I recommend disabling the script in your userscript manager and instead pasting it into the console while on the Plex web app. Any exceptions not from Plex itself, or log messages beginning with `[USERJS Plex Downloader]` would be helpful. Please redact any IP addresses or values for `X-Plex-Token=XXXXXXX` if you post these.

Second, visit https://app.plex.tv/desktop/#!/settings/manage-library-access and click on the account that is sharing this library with you, and check if it says "Downloads Allowed" under the "You have access to" section. If it does not, that may be the issue, but I would still like to add a feature where it tells you that is the reason why it is not working.

**Comment by kaizenGG** [comment]
Yes, I have access to 3 Plex servers, mine and 3 others.

But it only lets me download on my server, not on the others. And I bought Plex Pass

**Comment by kaizenGG** [comment]
![NjTC216](https://github.com/taxicat1/Plex-downloader/assets/23583436/48a89b41-c475-45ba-bf64-a2d26f9128f7)

**Comment by kaizenGG** [comment]
I've already tried several ways, and it only lets me download things from my own server on the same network. But not from other Plex servers

Do you have telegram or something?

**Comment by taxicat1** [comment]
You can contact my telegram `@taxicat`.

**Comment by taxicat1** [comment]
Issue was determined to be a typo in a XPath when parsing Plex resources that could cause downloads to use the wrong URI.
